### ISSUE TITLE
the last version breaks vite-plugin-md

### ISSUE THREAD

**Issue by hmt** [yankeeinlondon/happy-wrapper#2]
```
failed to load config from somedir/vite.config.ts
error during build:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined insomedir/node_modules/@yankeeinlondon/happy-wrapper/package.json
```

**Comment by hmt** [comment]
`vite-plugin-md` now works again with `@latest`. Thank you.

**Comment by yankeeinlondon** [comment]
@hmt is this still not working for you? It should be fine now. The issue was really multi-facetted and involved extracting sme CJS deps out of the toolchain.

**Comment by yankeeinlondon** [comment]
here's an example of it working with the latest `vite-plugin-md` and `happy-wrapper`: [test-md](https://github.com/yankeeinlondon/test-md)

**Comment by yankeeinlondon** [comment]
feel free to re-open if you're still experiencing it but please give me a reproduction

**Comment by hmt** [comment]
You're using vite 4 with Rollup 3. That might be able to fix the issue for you but since histoire is still on vite 3 we're currently stuck with it. My repo ist still throwing errors:

```
npm run build

> @svws-nrw/svws-client@0.4.2-SNAPSHOT build
> vite build

failed to load config from /Users/hmt/entwicklung/SVWS-Server/svws-webclient/src/webclient/ts/vite.config.ts
error during build:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/hmt/entwicklung/SVWS-Server/svws-webclient/node_modules/@yankeeinlondon/happy-wrapper/package.json
    at new NodeError (node:internal/errors:393:5)
    at exportsNotFound (node:internal/modules/esm/resolve:295:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:575:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/hmt/entwicklung/SVWS-Server/svws-webclient/node_modules/vite-plugin-md/dist/index.cjs:18031:28)
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @svws-nrw/svws-client@0.4.2-SNAPSHOT 
npm ERR!   at location: /Users/hmt/entwicklung/SVWS-Server/svws-webclient/src/webclient/ts 
```

Repo is at https://github.com/SVWS-NRW/SVWS-Server but kind of difficult to build. I think the main issue here is vite 3 vs vite 4

Thank you

**Comment by krystof-k** [comment]
Still not working, even after upgrading to Vite 4.0.1:

```
failed to load config from /Users/krystof.k/Git/kohovolit/volebni-kalkulacka-2022/frontend/vite.config.ts
error during build:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/krystof.k/Git/kohovolit/volebni-kalkulacka-2022/frontend/node_modules/@yankeeinlondon/happy-wrapper/package.json
    at new NodeError (node:internal/errors:393:5)
    at exportsNotFound (node:internal/modules/esm/resolve:295:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:575:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/krystof.k/Git/kohovolit/volebni-kalkulacka-2022/frontend/node_modules/vite-plugin-md/dist/index.cjs:18031:28)
```

**Comment by social4hyq** [comment]
> Still not working, even after upgrading to Vite 4.0.1:
> 
> ```
> failed to load config from /dev/vite.config.ts
> error during build:
> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /dev/node_modules/@yankeeinlondon/happy-wrapper/package.json
>     at new NodeError (node:internal/errors:393:5)
>     at exportsNotFound (node:internal/modules/esm/resolve:295:10)
>     at packageExportsResolve (node:internal/modules/esm/resolve:575:13)
>     at resolveExports (node:internal/modules/cjs/loader:538:36)
>     at Module._findPath (node:internal/modules/cjs/loader:607:31)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
>     at Module._load (node:internal/modules/cjs/loader:885:27)
>     at Module.require (node:internal/modules/cjs/loader:1105:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (/dev/node_modules/vite-plugin-md/dist/index.cjs:18031:28)
> ```

+1

**Comment by yankeeinlondon** [comment]
Your error indicates that you're trying to import from `main` not `module`. The issue is related to the fact that your end repo is using CJS. If you're using **vite** (either 3.x or 4.x) you should be able to just change your `package.json` to:

```json
{
   type: "module"
}
```

Then you'll all be parting with the ESM crowd instead of those old stodgy CJS'ers.

**Comment by krystof-k** [comment]
Thank you, using `"type": "module"` helped. I need to look further into this, I didn't realize that the Vue 3 scaffold still uses CJS.

**Comment by yankeeinlondon** [comment]
yeah well I think in the "broader world" CJS might be considered an "ok" default for web apps as most bundlers still prefer CJS as the export format but ViteJS (and for that matter Rollup) are of completely the opposite opinion :)

**Comment by yankeeinlondon** [comment]
Also if anyone is using the builders API's ... please use version `0.21.1` of **vite-plugin-md** and not the latest patch release. I accidently broke the type system on configuring these builders and am fixing right now but because I don't own the repo (or the **npm** permissions) I can't manually revoke these later releases.

**Comment by fengyuanchen** [comment]
@yankeeinlondon For some historical reasons, I can not use `type: "module"` in my project. Any solution?

**Comment by fengyuanchen** [comment]
VIte is ESM-first, but not ESM-must.

**Comment by fengyuanchen** [comment]
Anyway, thanks for your reply. I am using `vite-plugin-md@0.20.4` with `happy-dom@7.7.2`, and so far so good.

**Comment by yankeeinlondon** [comment]
> VIte is ESM-first, but not ESM-must.

For many people it has already switched to "ESM must" due to the ecosystem aggressively switching over now. It was for this reason that I finally took the plunge myself. I honestly think making the change now is a good call for most people. It's annoying to be forced to do something that doesn't move the bottom line forward but for most people it's really not hard at all.
